### PR TITLE
Pumpify "premature close" fix

### PR DESCRIPTION
**Pull request by phated**
@erikkemperman I'd love another pair of eyes on this to try to get it fixed correctly.

### CODE REVIEW

**Comment by phated** [comment]
@erikkemperman @terinjokes What do you guys think of this fix?  It seems to fix my pumpify issue while keeping the anti-Promise-swallowing test passing.

**Comment by phated** [comment]
Also, I linked it into https://github.com/cristianl/testcase-vinyl-bug and I see the actual error (ENOENT from fs-mkdirp-stream) instead of "Premature close"

**Comment by erikkemperman** [comment]
@phated That sounds like the proper fix here! Sorry I've been quiet, slightly insanely swamped at the moment...

**Comment by terinjokes** [comment]
LGTM

**Comment by phated** [comment]
Thanks all. I shipped this as 1.2.4 - now if only people would get it (have I mentioned how much I hate package-lock.json?)

**Pull request merged**
