### PR TITLE
Update project description

### LINKED ISSUE #37: Change project description
As I understand it, this is some sort of converter between async model conventions, but I'm unclear  when I'd use it.   I suggest a small scenario section at the top of the README might help clarify.

### PR DESCRIPTION
**Pull request by BurtHarris**
Fixes #37 

Note: Running npm@5, it generated a package-lock.json file.   I don't know much about that yet, but the message from npm suggested checking it in.

### CODE REVIEW

**Comment by phated** [comment]
I don't agree with the lock file. Please remove.

**Comment by BurtHarris** [comment]
Would you like me to use `git rebase -i master` to clean up the history?

**Comment by phated** [comment]
It's not necessary to rebase since github added the "squash and merge" button, but if you want to practice, I don't mind.

**Comment by BurtHarris** [comment]
@phated Thanks for the learning experience.   The rebase is easy, but leaves me unable to push.   Can you advise?   If its complex, please use the squash & merge thing.   Thanks

My status:

```
PS C:\code\async-done> git status
On branch description
Your branch and 'origin/description' have diverged,
and have 1 and 4 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
```

Then when I try to push it back to my GitHub fork, I get:

```
PS C:\code\async-done> git push
To https://github.com/BurtHarris/async-done.git
 ! [rejected]        description -> description (non-fast-forward)
error: failed to push some refs to 'https://github.com/BurtHarris/async-done.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by phated** [comment]
`git push -f` (force push, be careful)

**Comment by BurtHarris** [comment]
That worked, thanks.

**Comment by phated** [comment]
@BurtHarris this is a really great description.  Thanks!

**Pull request merged**
